Require TypeScript 3.6.x
We are using TypeScript 3.7+ in many places already, and the type definitions produced by that version
cannot be consumed in all cases by TypeScript 3.5 and lower:

```
error TS1086: An accessor cannot be declared in an ambient context.
```

See https://stackoverflow.com/a/59502221/196315 for a discussion.